#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX

#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16

#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define CAMERA_PIN_PWDN  GPIO_NUM_NC
#define CAMERA_PIN_RESET GPIO_NUM_NC
#define CAMERA_PIN_XCLK  GPIO_NUM_NC
#define CAMERA_PIN_SIOD  GPIO_NUM_38
#define CAMERA_PIN_SIOC  GPIO_NUM_39
#define CAMERA_PIN_D7    GPIO_NUM_42
#define CAMERA_PIN_D6    GPIO_NUM_46
#define CAMERA_PIN_D5    GPIO_NUM_45
#define CAMERA_PIN_D4    GPIO_NUM_20
#define CAMERA_PIN_D3    GPIO_NUM_19
#define CAMERA_PIN_D2    GPIO_NUM_9
#define CAMERA_PIN_D1    GPIO_NUM_18
#define CAMERA_PIN_D0    GPIO_NUM_48
#define CAMERA_PIN_VSYNC GPIO_NUM_40
#define CAMERA_PIN_HREF  GPIO_NUM_21
#define CAMERA_PIN_PCLK  GPIO_NUM_41
#define XCLK_FREQ_HZ     24000000

#define ML307_TX_PIN GPIO_NUM_11
#define ML307_RX_PIN GPIO_NUM_12
#define ML307_DTR_PIN GPIO_NUM_NC

#define PRESENCE_SENSOR_GPIO GPIO_NUM_47

#endif // _BOARD_CONFIG_H_
